# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-EOF
sudo apt-get update
sudo apt-get install apache2 -y
EOF


Vagrant.configure("2") do |config|
  config.vm.define "server1" do |server1|
    server1.vm.box = "ubuntu/focal64"
    server1.vm.network "private_network", ip: "10.10.10.11"
    #server1.vm.provider "virtualbox" do |vb|
    #vb.memory = 1024
    # vb.cpus = 2
  end
  #config.vm.define "server2" do |server2|
   # server2.vm.box = "centos/7"
   # server2.vm.network "private_network", ip: "10.10.10.12"

  #end
end
